### ISSUE TITLE
more Initialize checks

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#106]
It would help to add this intializer checks to avoid user error:

1. Alert user if a package called in the run_model.R script does not appear in
/defs/run_model_parameters.json .  It appears that at least in some cases, the run_model.R script package is used, but can often cause an error downstream.

I've had this be caught before, but not consistently.

**Comment by jrawbits** [comment]
I think this is no longer a problem in VEModel (which does more careful module checking). Can we verify it with the current development-next (2022-01)?
