### ISSUE TITLE
quick input file documentation fix

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#115]
Documentation needs link to list of allowable entries for UzaNameLookup field in VERSPM marea_base_year_dvmt.csv input file.

Here are the allowable entries:
https://github.com/VisionEval/VisionEval/blob/master/sources/modules/VETravelPerformance/inst/module_docs/Initialize.md

Here is input file description that needs more detailed link to allowable entries:  (#2)
https://github.com/VisionEval/VisionEval-Dev/blob/readme-dev/docs/tutorials/verspm/Modules_and_Outputs.md/#initialize-vetravelperformance

**Comment by jrawbits** [comment]
Can we maybe sweep this up in the Pooled Fund Phase 2.0 contract documentation task?
