### ISSUE TITLE
ve.build fails on macOS when there is a space in the pathname

### ISSUE THREAD

**Issue by jpn--** [VisionEval/VisionEval-Dev#129]
My ve.build() call fails when there is a space in the full path name leading to the VisionEval directory.  

A workaround is to move the entire directory so that there's no space in the path, although obviously it would be more convenient if I could install where I like.  I recognize that this is a low priority fix given the platform and the available workaround, but I thought I'd leave this issue here as a record that it exists.

**Comment by jrawbits** [comment]
Thanks for the report. It appears to be a quoting problem when the external process that do the build are invoked.

**Comment by jrawbits** [comment]
I'm going to close this issue, but leave the related #102 (Macintosh build) open.
