### ISSUE TITLE
splitInt() function in AssignLocTypes can fail to correctly allocate right number of dwelling units

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VisionEval-Dev#144]
Here is the [splitInt() function](https://github.com/VisionEval/VisionEval-Dev/blob/6c24ed6d34c06afd908e3fc7571d4edd885041d6/sources/modules/VELandUse/R/AssignLocTypes.R#L320) in the AssignLocTypes module:

```
# Define a function to do a whole number splitting according to proportions
splitInt <- function(Props_, Tot) {
  SplitAll_ <- Props_ * Tot
  SplitInt_ <- round(SplitAll_)
  Rem <- sum(SplitAll_ - SplitInt_)
  if (Rem != 0) {
    RemTab_ <- table(
      sample(1:length(Props_), abs(Rem), replace = TRUE, prob = Props_)
    )
    SplitInt_[as.numeric(names(RemTab_))] <-
      SplitInt_[as.numeric(names(RemTab_))] + sign(Rem) * RemTab_
  }
  SplitInt_
}
```

This works by feeding a dataframe of proportions of land types 'Lt' (urban, town, rural) by housing type 'Ht' (single family, multifamily, group quarters) for each Bzone 'Bz'. This is stored in the 3-dimensinal array Props_BzHtLt.
Those proportions are then applied to the vector describing the number of housing types for each Bzone, stored in the 2-dimensional array DU_BzHt_full, [here](https://github.com/VisionEval/VisionEval-Dev/blob/6c24ed6d34c06afd908e3fc7571d4edd885041d6/sources/modules/VELandUse/R/AssignLocTypes.R#L341).

```
  # Calculate dwelling units by Bzone, housing type and location type
  DU_BzHtLt <- sweep(Props_BzHtLt, c(1,2), DU_BzHt_full, splitInt)
```

For one particular set of inputs I'm working with, this is now failing to correctly apply the splitInt, resulting in a mismatch between the length of the vector of names and housing IDs. The error occurs in the double loop [here in ](https://github.com/VisionEval/VisionEval-Dev/blob/6c24ed6d34c06afd908e3fc7571d4edd885041d6/sources/modules/VELandUse/R/AssignLocTypes.R#L352 )AssignLocTypes.R.

Problem: The resulting DU_BzHtLt for this Bzone and housing type only sums to 984, but there are 985 dwelling units in this Bzone for the SF housing type. First, showing how it is supposed to work (and does, when manually feeding in data):

```
Props_ = c(0.0, 0.9, 0.1)
names(Props_) = c("Urban", "Town", "Rural")

Tot = 985

result <- splitInt(Props_, Tot)

> result
Urban  Town Rural 
    0   887    98 

sum(result) # 985
```

So what's the issue?

```
# Here are the actual inputs
> Props_BzHtLt[228,1,]
Urban  Town Rural 
  0.0   0.9   0.1 
> DU_BzHt_full[228,1]
[1] 985

# Now we feed these to splitInt()
Props_ = Props_BzHtLt[228,1,]
Tot = DU_BzHt_full[228,1]

result <- splitInt(Props_, Tot)

> result
Urban  Town Rural 
    0   886    98 

sum(result) # 984 !!!
```

**Comment by jrawbits** [comment]
It's almost certainly a rounding error. I'll add some internal cross-checking...

From: dflynn-volpe ***@***.***>
Sent: Wednesday, May 5, 2021 8:22 AM
To: VisionEval/VisionEval-Dev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VisionEval/VisionEval-Dev] splitInt() function in AssignLocTypes can fail to correctly allocate right number of dwelling units (#144)

CAUTION: This email originated from outside of the Department of Transportation (DOT). Do not click on links or open attachments unless you recognize the sender and know the content is safe.


Here is the splitInt() function<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVisionEval%2FVisionEval-Dev%2Fblob%2F6c24ed6d34c06afd908e3fc7571d4edd885041d6%2Fsources%2Fmodules%2FVELandUse%2FR%2FAssignLocTypes.R%23L320&data=04%7C01%7Cjeremy.raw%40dot.gov%7C4a3f1bb7b6ae45c7751808d90fc0649b%7Cc4cd245b44f04395a1aa3848d258f78b%7C0%7C0%7C637558141259900668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Qk2uqeuSNGxvevGBR80BaMb7ujTr6qxYzPvoBpi7VJk%3D&reserved=0> in the AssignLocTypes module:

# Define a function to do a whole number splitting according to proportions

splitInt <- function(Props_, Tot) {

  SplitAll_ <- Props_ * Tot

  SplitInt_ <- round(SplitAll_)

  Rem <- sum(SplitAll_ - SplitInt_)

  if (Rem != 0) {

    RemTab_ <- table(

      sample(1:length(Props_), abs(as.integer(Rem)), replace = TRUE, prob = Props_)

    )

    SplitInt_[as.numeric(names(RemTab_))] <-

      SplitInt_[as.numeric(names(RemTab_))] + sign(Rem) * RemTab_

  }

  SplitInt_

}

This works by feeding a dataframe of proportions of land types 'Lt' (urban, town, rural) by housing type 'Ht' (single family, multifamily, group quarters) for each Bzone 'Bz'. This is stored in the 3-dimensinal array Props_BzHtLt.
Those proportions are then applied to the vector describing the number of housing types for each Bzone, stored in the 2-dimensional array DU_BzHt_full, here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVisionEval%2FVisionEval-Dev%2Fblob%2F6c24ed6d34c06afd908e3fc7571d4edd885041d6%2Fsources%2Fmodules%2FVELandUse%2FR%2FAssignLocTypes.R%23L341&data=04%7C01%7Cjeremy.raw%40dot.gov%7C4a3f1bb7b6ae45c7751808d90fc0649b%7Cc4cd245b44f04395a1aa3848d258f78b%7C0%7C0%7C637558141259900668%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=poGmmSPu5j4bbYSUmFWn3G%2FPvwNMAzO5LD9RGkM%2BsvE%3D&reserved=0>.

  # Calculate dwelling units by Bzone, housing type and location type

  DU_BzHtLt <- sweep(Props_BzHtLt, c(1,2), DU_BzHt_full, splitInt)

For one particular set of inputs I'm working with, this is now failing to correctly apply the splitInt, resulting in a mismatch between the length of the vector of names and housing IDs. The error occurs in the double loop here in <https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVisionEval%2FVisionEval-Dev%2Fblob%2F6c24ed6d34c06afd908e3fc7571d4edd885041d6%2Fsources%2Fmodules%2FVELandUse%2FR%2FAssignLocTypes.R%23L352&data=04%7C01%7Cjeremy.raw%40dot.gov%7C4a3f1bb7b6ae45c7751808d90fc0649b%7Cc4cd245b44f04395a1aa3848d258f78b%7C0%7C0%7C637558141259910624%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m062kxY6f0ivcC9xTJHdPgIEjJXwhZW9AMZEEnbV9co%3D&reserved=0> AssignLocTypes.R.

Problem: The resulting DU_BzHtLt for this Bzone and housing type only sums to 984, but there are 985 dwelling units in this Bzone for the SF housing type:

Props_ = c(0.0, 0.9, 0.1)

names(Props_) = c("Urban", "Town", "Rural")



Tot = 985



result <- splitInt(Props_, Tot)



sum(result) # 985

So what's the issue?

# Here are the actual inputs

> Props_BzHtLt[228,1,]

Urban  Town Rural

  0.0   0.9   0.1

> DU_BzHt_full[228,1]

[1] 985



# Now we feed these to splitInt()

Props_ = Props_BzHtLt[228,1,]

Tot = DU_BzHt_full[228,1]



result <- splitInt(Props_, Tot)



sum(result) # 984 !!!

-

**Comment by dflynn-volpe** [comment]
Yep, here's a possible solution (using the real inputs):

```
# Here are the first few lines of splitInt():
SplitAll_ <- Props_ * Tot
SplitInt_ <- round(SplitAll_)
Rem <- sum(SplitAll_ - SplitInt_)

# Rem = 1, meaning that we are off by 1 and need to sample from the proportions to assign one DU to a land use type
sample(1:length(Props_), abs(Rem), replace = TRUE, prob = Props_)
# This is the problem, it produces no result:
# integer(0) 
```
If we add a rounding step to ensure that our remainder is an integer, this succeeds:

```
Rem = round(Rem, 0)

sample(1:length(Props_), abs(Rem), replace = TRUE, prob = Props_)
# [1] 2
```

I will push a fix to development after testing that this works.

**Comment by dflynn-volpe** [comment]
Slightly different. The right way to think about the inputs to splitInt() is that the 2-D array `DU_BzHt_full` is applied to each 2-D slice of the array `Props_BzHtLt` (one slice for each land use type). 

The problem is that in the particular inputs I'm using, the remainder `Rem` for the Town slice is not an integer! It comes out to 2.5. The `sample()` function requires the size parameter (Rem) to be an integer. This might mean re-configuring this step so that it applies the number of dwelling units by land use type separately for each Bzone; currently it is set up to go across Bzones, within each land use type.

**Comment by dflynn-volpe** [comment]
Fixing in [patch_splitInt](https://github.com/VisionEval/VisionEval-Dev/tree/patch_splitInt)

**Comment by jrawbits** [comment]
Fix is in the pipeline

**Comment by jrawbits** [comment]
Fixed in development-next push 2023-03-24
