### ISSUE TITLE
Description of ElecDvmtProp in AssignHhVehiclePowertrain Module

### ISSUE THREAD

**Issue by shichenfan** [VisionEval/VisionEval-Dev#151]
In the code and documentation [VE_Training.md](https://github.com/visioneval/VisionEval/blob/master/sources/modules/VEPowertrainsAndFuels/inst/module_docs/AssignHhVehiclePowertrain.md) & [Modules_and_Outputs.md
](https://github.com/VisionEval/VisionEval-Docs/blob/master/tutorials/verspm/Modules_and_Outputs.md#assignhhvehiclepowertrain), the description of outcome **_'ElecDvmtProp'_** is ‘Average miles of vehicle travel per gasoline equivalent gallon (fuel and electric powered)’.
It seems should be "Proportion of DVMT powered by electricity".

**Comment by jrawbits** [comment]
I'll make that description change in the development branch: it's just a description problem (incomplete cut-and-paste in creating the variable specification).  Two places:

VETravelPerformance:::AdjustHhVehicleMpgMpkwh.R : line 371 (plus add more specific description of algorithm to module docs at the top of the file)
VEPowertrainsAndFuels::AssignHvVehiclePowertrain.R: line 575 (plus module docs at top of file, change "ElecProp" in pseudo-code description to "ElecDvmtProp")

New description will be as Shichen proposes. We will need to change the secondary documentation as well.
