### ISSUE TITLE
UX - create cloud-based demo version

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VisionEval-Dev#21]
Originally created by @bstabler June 2018:

It would be great to have a cloud-based version of VE. For example, visioneval.org/demo should run the version of RPAT and RSPM in the test system. Eventually we may be able to allow users to create and run their own scenarios in the cloud, but for now, just doing the demo online would be great for new users, outreach, etc.

**Comment by jrawbits** [comment]
Not clear what such a "demo" might be. It's pretty painless these days just to install VisionEval and run one of the test models (e.g. via the walkthrough). I think it would be more helpful to do some introductory videos to show what it looks like (and walk people through doing it on their own computer).

**Comment by jrawbits** [comment]
I'm closing this issue and will add a new one that describes desirable training materials - videos, walkthrough code, etc that people can run from the VisionEval installer.
