### ISSUE TITLE
Error when TotEmp field of bzone_employment.csv contains 0 value

### ISSUE THREAD

**Issue by shichenfan** [VisionEval/VisionEval-Dev#39]
When TotEmp field of bzone_employment.csv contains 0 value, get error as below:
![error_employ](https://user-images.githubusercontent.com/34109093/57800691-00f18d80-7720-11e9-91ec-e83ebf1aac4e.PNG)
bzone_employment.csv is an input of LocateEmployment Module. 
Model got error in 'Calculate4DMeasures' step

**Comment by dflynn-volpe** [comment]
Notes from Chi Ping:

First,  VERSPM could not run to completion if there is BZONE with zero employment. The error occurs in LocateEmployment module when it adjusts the regional employment to the number of workers:
``` 
    TotEmp_Bz <- colSums(WkrOD_BzBz)
    RetEmp_Bz <- round(TotEmp_Bz * (L$Year$Bzone$RetEmp/L$Year$Bzone$TotEmp))
    SvcEmp_Bz <- round(TotEmp_Bz * L$Year$Bzone$SvcEmp/L$Year$Bzone$TotEmp)
```
If the TotEmp for a Bzone is zero, R will return the NA value to RetEmp_Bz and SvcEmp_Bz. Any NA value will cause fatal error down the road. Hopefully this will be addressed. 

Second, by matching the total employment to the total number of workers, VERSPM implicitly assumes that all workers works inside the Metropolitan area. This implicit assumption may not be true if VERSPM is applied to the a region where there are significant workers coming from outside region or going out of the region (like Washington DC) or to a subregion of a Metropolitan area.  I wish the documentation will discuss applying VisionEval to such region with significant imbalance between number of workers and employments.

**Comment by dflynn-volpe** [comment]
I have rediscovered this old issue with new inputs. I have a [patch in progress here](https://github.com/VisionEval/VisionEval-Dev/tree/patch_LocateEmp).
