### ISSUE TITLE
Error in BudgetHouseholdDvmt for year 2005

### ISSUE THREAD

**Issue by dsrosenthal5** [VisionEval/VisionEval-Dev#45]
I'm thinking there is an issue running a 2005 base year related to Vehicle Ownership Cost. I have a 2005 base year and 2040 future year. When I run the model it fails during the BudgetHouseholdDvmt module with the error: "Error in quantile.default(AdjDvmt_Hh, 0.01) : missing values and NaN's not allowed if 'na.rm' is FALSE."

When I open the "AveVehCostPM.Rda" it is entirely populated with NaN values.

I tested the same input files but changed the base year to 2010 and the model ran through.

It seems like there are some year assumptions in the "CalculateVehicleOperatingCost" script but I haven't been able to trace the issue.

Any suggestions on places where a base year of 2005 may cause an issue?

**Comment by arashasadabadi** [comment]
@dsrosenthal5 Would you please share the 2005 data you are running the VERSPM with? ( share it via a link or push it to visioneval_dev)

**Comment by dsrosenthal5** [comment]
@arashasadabadi here is the link, let me know if you have any issues, thanks!

https://drive.google.com/drive/folders/13d96qxEdRLacOHFSpxHcSYD_Du1MUma-?usp=sharing

**Comment by arashasadabadi** [comment]
@dsrosenthal5 I debugged the error and it goes three levels back where "AssignHhVehiclePowertrain" module in "VEPowertrainsAndFuels" generates "MPG" variable for vehicles. it produces the "NA" values and it cascades to downstream modules where we see the error you mentioned. 


To fix it , we need to modify the  ldv_powertrain_characteristics.csv file located in "…\VEPowertrainsAndFuels\inst\extdata\ "and update the VEPowertrainsAndFuels package . Currently, the powertrain characteristics for year 2005 and before is all "NA" values. This makes a problem when calculating the average MPG for vehicles whose make year is 2005 or older. ( for the original case where the base year was 2010, data had at least one 'non-NA' value belongs to 2010 when calculating the mean, now all the values for 2005 and before are 'NA' and the average would also be 'NA')


As an example I updated the  "ldv_powertrain_characteristics.csv" with the 2005 values set to 2010 values ( in the real example you may need to extract the real data for 2005 year) and then updated the package and re-install it. Now the run goes through successfully.

**Comment by dflynn-volpe** [comment]
@arashasadabadi can you see if you can remove NA values at [this step](https://github.com/VisionEval/VisionEval-Dev/blob/development/sources/modules/VEPowertrainsAndFuels/R/AssignHhVehiclePowertrain.R#L893) in the VEPowertrainsAndFuels package, rather than manually putting in 2010 values?

**Comment by dsrosenthal5** [comment]
@arashasadabadi @dflynn-volpe I think it was partially successful. Implementing the change in ldv_powertrain_characteristics.csv does result successful model run however all of the Commercial Vehicle emissions outputs from the "CalculateComEnergyAndEmissions" module within VETravelPerformance are not getting calculated for 2005, they return either NaN or NA. I'm not sure if this is a different issue but it seems related, at least to a model year of 2005.

**Comment by arashasadabadi** [comment]
@dsrosenthal5 The new error you found is in the continuation of the previous one. This time The "NA" values for year 2000 in the "hvytrk_powertrain_characteristics.csv" and "transit_powertrain_characteristics.csv"  located in "…\VEPowertrainsAndFuels\inst\extdata\ " causes the problem. When I tracked the source of error, I found out the script uses an interpolation method to estimate the ICEV,BEV and HEV MPG of the model year from the existing data. For instance, in the case of Model year "2005", it uses "2000" and "2010" to estimate "2005" values but since the 2000 values are "NA" this results to NA values for MPG which eventually will be reflected in the emission results. I did the same approach as I replaces the "NA" values of year 2000 with 2010 values and updated and re-installed the package. This will lead to non-NA emission values. 

Again, this is a temporary solution. ( with applying this change, we are assuming 2005 MPG data are same with 2010)

**Comment by dsrosenthal5** [comment]
@arashasadabadi I implemented the change in those files and I am still getting NA values for ComSvcAveUrbanAutoCO2eRate and ComSvcAveUrbanLtTrkCO2eRate. Were those values populated for you?

**Comment by arashasadabadi** [comment]
@dsrosenthal5 They are populated for me ( .443 and .627 respectively). How did you re-install the packages? Are you using the installer? if it is re-installed with the changes to 2000 data in those two input files, you should see the updates in the "PowertrainFuelDefaults_ls.rda" data list in "VEPowertrainsAndFuel" package. Are you seeing that change?

By the way how do you check the outputs of the model? Do you open the RDA files from datastore?

**Comment by dsrosenthal5** [comment]
@arashasadabadi I've been rebuilding using the 'install.R' script and just commenting the modules I don't need to rebuild. This builds the VEPowertrainAndFuels package with the modified extdata but there isn't a PowertrainFuelDefaults_ls.rda in the VEPowertrainAndFuels package in my library. The original PowertrainFuelDefaults_ls.rda in the zip is not modified by the 'install.R' script when I do this. Sounds like I am missing something?

I've been checking rda file value from the datastore using Rstudio, at least for the Marea values it is easy.

**Comment by arashasadabadi** [comment]
@dsrosenthal5 Thanks. Would you please redo the installation, restart the Rstudio and then check the library data by using "VEPowertrainsAndFuels::PowertrainFuelDefaults_ls$HvyTrkPowertrainCharacteristics_df" command and see if the 2000 data has been modified?

(Note that the zip file shouldn't change. Also you don't have access to the R data sets as RDA format in the library. )

**Comment by dsrosenthal5** [comment]
@arashasadabadi The value for HvyTrkPowertrainCharacteristics_df did not update but the extdata file is updated.

**Comment by dsrosenthal5** [comment]
Rebuilding the VEPowertrainsAndFuels module using devtools::check("path/to/file/VEPowertrainsAndFuels") and then reinstalling successfully updated the module, thanks!

**Comment by arashasadabadi** [comment]
@jrawbits We had to do the devtool:check() to update the data files . Again, install command is not updating the data files.

**Comment by jrawbits** [comment]
@arashasadabadi  See this issue for further discussion: [https://github.com/VisionEval/VE-Installer/issues/13](https://github.com/VisionEval/VE-Installer/issues/13)
