### ISSUE TITLE
model_pearameters.json -- add reference for default value

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#6]
I want to add this documentation for a default value in model_parameters.json. Not sure if this is the correct location, and so not doing a pull request... -- Tara

Existing VE-RSPM documentation of this file is found here:  [VisionEval-Dev/docs/tutorials/verspm/](https://github.com/VisionEval/VisionEval-Dev/edit/readme-dev/docs/tutorials/verspm/Inputs_and_Parameters.md) 

Update to documentation is in bold below:
model_parameters.json
This file contains global parameters for a particular model configuration that may be used by multiple modules. A more detailed description of the file and its structure can be found here. The format of this file is as followsfollows. **The source of the default $16/hr is per a [Nov 2016 ODOT Report:](https://www.oregon.gov/ODOT/Data/Documents/The-Value-of-Travel-Time-2015.pdf) "The Value of Travel-Time: Estimates of the Hourly Value of Time for Vehicles in Oregon 2015")**:

[
  {"NAME": "ValueOfTime", 
   "VALUE": "16", 
   "TYPE": "double", 
   "UNITS": "base cost year dollars per hour"
  }
]
Top

**Comment by dflynn-volpe** [comment]
Hi Tara / @mrspeel - Yes, this is a good place to start an issue like this, I'll take a look and keep you updated here.

**Comment by dflynn-volpe** [comment]
Closed by 7118ec6
