### ISSUE TITLE
fix broken link in documentation

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#80]
Reference to ODOT report on this page has changed: 
https://github.com/VisionEval/VisionEval-Dev/blob/readme-dev/docs/tutorials/verspm/Inputs_and_Parameters.md#model_parametersjson

Here is the correct link: 
https://www.oregon.gov/ODOT/Data/Documents/Value-of-Travel-Time-for-Vehicles.pdf

**Comment by jrawbits** [comment]
Fixed in commit 9b1c948fc00d2961e056d2821a1f501c2662f2e8
