### ISSUE TITLE
Module dataset specifications inconsistencies show up when loading datastore but not otherwise

### ISSUE THREAD

**Issue by gregorbj** [VisionEval/VisionEval-Dev#90]
When datastore loading was implemented and tested, a number of dataset specification inconsistencies showed up when initializeModel was called that did not show up without loading a datastore. The checking of dataset specification consistency does not appear to be happening correctly when a datastore is not being loaded.

**Comment by jrawbits** [comment]
We'll probably need a bit more information about the problem of checking internal dataset specification inconsistency to deal with it successfully...

**Comment by jrawbits** [comment]
The 2023-03-24 development-next push does implement LoadDatastore functionality and it does work; this bug may still be hanging out, but we'll wait for a use case that exposes it.
